### PR TITLE
In Japanese Morse, yi to wyi, ye to wye

### PR DESCRIPTION
**Pull request by nuko0134**
Nice to meet you.

I think the characters "ゐ、ヰ" and the commented out "ゑ、ヱ" in the Japanese Morse correspondence table in line 390 and 410 are incorrect.

I think the correct characters are "yi" for "wyi" and "ye" for "wye".

I'm sorry if this is unnecessary.

### CODE REVIEW

**Comment by qsantos** [comment]
Hello @komugikotan,

Thanks for having taken the time to report this. However, my understanding is that `wyi` and `wye` are the sequence of letters to type to get these characters with most IMEs. However, I think the correct translitteration is still [`wi`](https://en.wikipedia.org/wiki/Wi_(kana)) and [`we`](https://en.wikipedia.org/wiki/We_(kana)), so I do not think a change is warranted in this case.

**Comment by nuko0134** [comment]
Thank you for the reply!

Yes, I think you are correct. I'll just change yi to wi and ye to we and recommit it.
(If you want to commit it's fine)

This is my mistake, which happened due to the narrowness of my knowledge even though I am Japanese. Thank you for making me aware of my mistake.

**Comment by qsantos** [comment]
I had totally missed that it was initially yi/ye and not wi/we. So it was much more my mistake than yours! Thanks for your patience.

@dj1yfk 
The correct names for these characters are indeed wi/we, and @komugikotan'PR does fix a code documentation bug. You can check the Wikipedia pages for [wi](https://en.wikipedia.org/wiki/Wi_(kana)) and [we](https://en.wikipedia.org/wiki/We_(kana)) and compare the shape of the character to confirm yourself.

**Comment by nuko0134** [comment]
Thank you for the reply!

**Comment by dj1yfk** [comment]
@komugikotan Thanks for the PR, and sorry for the long delay in processing it.
@qsantos  Thanks for your fix, too!

**Comment by nuko0134** [comment]
Thank you too!

**Pull request merged**
